name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches: ['*']

  workflow_dispatch:

jobs:
  main:
    name: Validate and Deploy
    runs-on: ubuntu-latest

    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Cache Packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        timeout-minutes: 1

      - name: Install Packages
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$GH_PACKAGES_TOKEN
          npm config set @by-intera:registry=https://npm.pkg.github.com
          npm ci
        timeout-minutes: 3

      - name: Publish Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          npm config set @by-intera:registry=https://npm.pkg.github.com
          npm publish
